(function () {
  "use strict";

  const quotes = [
    "Tu n'as pas besoin de tout faire aujourd'hui. Un petit pas suffit.",
    "Chaque petit pas compte.",
    "Tu avances déjà.",
    "La perfection n'est pas nécessaire.",
    "Une maison plus légère commence par une seule action.",
    "Quinze minutes peuvent changer une journée.",
    "Faire un peu, c'est déjà faire.",
    "Ton énergie mérite d'être respectée.",
    "Choisis le plus petit geste possible.",
    "Le calme se construit doucement.",
    "Tu peux t'arrêter après ce petit pas.",
    "Aujourd'hui n'a pas besoin d'être parfait.",
    "Une surface dégagée peut offrir un peu d'air.",
    "Le progrès discret reste du progrès.",
    "Commence là où tes yeux se posent.",
    "Moins de pression, plus de douceur.",
    "Tu n'es pas en retard. Tu recommences simplement.",
    "Ton espace peut évoluer à ton rythme.",
    "Même deux minutes ont de la valeur.",
    "Ce que tu fais maintenant est suffisant.",
    "Avance avec ton énergie, pas contre elle.",
    "Une chose à la fois, puis une pause.",
    "Tu peux choisir la facilité aujourd'hui.",
    "Petit ne veut pas dire insignifiant.",
    "Prendre soin de ton espace, c'est aussi prendre soin de toi.",
    "La constance douce vaut mieux que l'effort parfait.",
    "Il n'y a rien à rattraper.",
    "Tu as le droit de simplifier.",
    "Un coin apaisé suffit pour commencer.",
    "Respire. Choisis une chose. C'est tout."
  ];

  const missions = [
    { title: "Libérer un tiroir", description: "Choisis un seul tiroir. Garde ce qui est utile, puis arrête-toi quand le minuteur sonne.", minutes: 10 },
    { title: "Faire briller l'évier", description: "Vide l'évier, rince-le et essuie rapidement le contour. Pas besoin de toucher au reste.", minutes: 8 },
    { title: "Dégager une tablette", description: "Retire ce qui n'a plus sa place sur une tablette visible et remets seulement l'essentiel.", minutes: 10 },
    { title: "Ramasser le salon", description: "Prends un panier et rassemble les objets qui appartiennent à une autre pièce.", minutes: 7 },
    { title: "Rafraîchir le réfrigérateur", description: "Jette un aliment périmé et essuie une seule tablette. Cette petite victoire suffit.", minutes: 10 },
    { title: "Room Rescue express", description: "Choisis la pièce qui te pèse le plus et range seulement ce qui est évident.", minutes: 5 },
    { title: "Dégager une chaise", description: "Retire tout ce qui s'est accumulé sur une chaise et redonne-lui sa fonction.", minutes: 5 },
    { title: "Trier le courrier", description: "Fais trois piles : agir, garder, recycler. Ne traite rien d'autre pour l'instant.", minutes: 8 },
    { title: "Nettoyer un miroir", description: "Choisis le miroir le plus utilisé et essuie-le, sans ajouter d'autre tâche.", minutes: 5 },
    { title: "Rassembler les tasses", description: "Fais un petit tour et rapporte seulement les verres et les tasses à la cuisine.", minutes: 4 },
    { title: "Dompter un Hot Spot", description: "Choisis une petite surface où les objets s'accumulent et replace cinq choses.", minutes: 5 },
    { title: "Préparer demain", description: "Dépose tes vêtements ou les essentiels de demain au même endroit.", minutes: 6 },
    { title: "Vider une poubelle", description: "Choisis une seule petite poubelle, vide-la et remets un sac propre.", minutes: 4 },
    { title: "Plier dix morceaux", description: "Plie ou suspends exactement dix vêtements, puis autorise-toi à arrêter.", minutes: 8 },
    { title: "Nettoyer une poignée", description: "Essuie les poignées les plus touchées dans une seule pièce.", minutes: 5 },
    { title: "Créer un panier de départ", description: "Rassemble les objets à donner dans un sac ou un panier clairement identifié.", minutes: 8 },
    { title: "Dégager la table", description: "Libère juste assez d'espace pour y déposer un repas ou une tasse.", minutes: 7 },
    { title: "Balayer une zone", description: "Choisis un petit passage très fréquenté et balaie seulement cet endroit.", minutes: 6 },
    { title: "Ranger les chaussures", description: "Aligne ou range les chaussures près de l'entrée. Ignore le reste de la pièce.", minutes: 5 },
    { title: "Faire le tour des déchets", description: "Avec un sac, ramasse uniquement ce qui est clairement à jeter.", minutes: 6 },
    { title: "Rafraîchir la toilette", description: "Nettoie rapidement le siège et la cuvette. Une version simple est parfaite.", minutes: 8 },
    { title: "Réunir les produits", description: "Regroupe les produits de soin qui traînent dans un seul contenant.", minutes: 6 },
    { title: "Changer les serviettes", description: "Remplace les serviettes de la salle de bain et mets les autres au lavage.", minutes: 5 },
    { title: "Faire le lit simplement", description: "Remonte la couverture et place les oreillers. Pas besoin d'un résultat parfait.", minutes: 3 },
    { title: "Sauver la table de chevet", description: "Jette les déchets et garde seulement trois objets utiles sur la surface.", minutes: 7 },
    { title: "Trier un sac", description: "Vide un sac à main, un sac à dos ou un sac réutilisable, puis replace l'essentiel.", minutes: 10 },
    { title: "Ranger cinq objets", description: "Choisis cinq objets visibles et ramène-les à leur place.", minutes: 4 },
    { title: "Essuyer le comptoir", description: "Dégage et essuie une section de comptoir, même si le reste attend.", minutes: 6 },
    { title: "Vérifier les restes", description: "Regarde les contenants au frigo et décide simplement : garder, congeler ou jeter.", minutes: 8 },
    { title: "Préparer une station d'eau", description: "Place une bouteille ou un verre d'eau à un endroit où tu le verras.", minutes: 3 },
    { title: "Nettoyer la télécommande", description: "Essuie les télécommandes et replace-les dans un endroit facile à retrouver.", minutes: 4 },
    { title: "Libérer le sol", description: "Ramasse seulement ce qui bloque le passage dans une pièce.", minutes: 6 },
    { title: "Choisir une boîte", description: "Ouvre une seule petite boîte et décide du sort de cinq objets.", minutes: 10 },
    { title: "Rassembler les câbles", description: "Regroupe les câbles visibles et retire ceux qui ne servent plus.", minutes: 8 },
    { title: "Rafraîchir l'entrée", description: "Secoue le tapis ou essuie rapidement le seuil de la porte.", minutes: 5 },
    { title: "Classer cinq papiers", description: "Traite cinq papiers seulement : recycler, archiver ou mettre à l'action.", minutes: 6 },
    { title: "Créer un coin calme", description: "Dégage un petit espace où poser une boisson, un livre ou simplement tes mains.", minutes: 8 },
    { title: "Lancer une machine", description: "Rassemble une brassée simple et démarre-la. La suite pourra attendre.", minutes: 7 },
    { title: "Remettre les coussins", description: "Replace les coussins et plie une couverture pour apaiser visuellement le salon.", minutes: 4 },
    { title: "Nettoyer une étagère de douche", description: "Retire les contenants vides et rince une seule tablette.", minutes: 7 },
    { title: "Faire une pause panier", description: "Pendant cinq minutes, remplis un panier avec les objets qui n'ont pas leur place ici.", minutes: 5 },
    { title: "Préparer une sortie facile", description: "Place clés, portefeuille et sac près de la porte pour alléger demain.", minutes: 4 }
  ];

  const tipActions = [
    "Prépare les vêtements du lendemain avant de te coucher.",
    "Fais briller l'évier pour créer un point de départ visuel.",
    "Gère un Hot Spot pendant seulement deux minutes.",
    "Utilise un minuteur visible plutôt que ta motivation.",
    "Désencombre avant d'acheter des contenants.",
    "Garde un panier pour les objets qui appartiennent ailleurs.",
    "Place les objets à l'endroit où tu les utilises vraiment.",
    "Commence par les déchets : la décision est plus facile.",
    "Choisis une surface de la taille d'une feuille de papier.",
    "Laisse les produits de nettoyage près de leur zone d'usage.",
    "Crée une maison simple pour tes clés.",
    "Range les objets fréquents entre la taille et les yeux.",
    "Limite-toi à cinq objets quand l'énergie est basse.",
    "Associe une mini-tâche à une habitude déjà installée.",
    "Prends une photo avant de commencer pour voir le progrès.",
    "Utilise des bacs ouverts si les couvercles deviennent un obstacle.",
    "Étiquette avec des mots simples et visibles.",
    "Mets un petit sac à déchets dans chaque zone utile.",
    "Garde un chiffon accessible pour les nettoyages spontanés.",
    "Décide à l'avance de ce que signifie « assez propre ».",
    "Réduis le nombre d'étapes entre utiliser et ranger.",
    "Fais une tournée des tasses une fois par jour.",
    "Transforme l'attente du micro-ondes en minute de rangement.",
    "Laisse un espace vide dans chaque tiroir.",
    "Choisis un seul type d'objet à trier à la fois.",
    "Range d'abord ce qui a déjà une place.",
    "Utilise une liste de trois tâches maximum.",
    "Commence par la pièce qui te rendrait la vie plus facile.",
    "Pose un panier de dons à un endroit accessible.",
    "Prends la décision la plus simple, pas la plus parfaite.",
    "Ferme la cuisine avec un rituel de cinq minutes.",
    "Prépare les produits avant de lancer le minuteur.",
    "Fais le lit dans sa version la plus simple.",
    "Garde les surfaces visibles aussi libres que possible.",
    "Regroupe les objets similaires avant de les organiser.",
    "Mets les choses importantes dans ton champ de vision.",
    "Utilise des rappels positifs plutôt que des reproches.",
    "Fais une pause avant d'ajouter une nouvelle tâche.",
    "Choisis une catégorie facile pour créer de l'élan.",
    "Nettoie de haut en bas pour éviter de recommencer.",
    "Garde une boîte « à décider » avec une date limite.",
    "Prévois un endroit pour les vêtements portés mais encore propres.",
    "Mets les sacs réutilisables près de la porte.",
    "Simplifie un rangement qui t'agace souvent.",
    "Range pendant la durée d'une seule chanson.",
    "Commence dans le coin le plus visible de la pièce.",
    "Laisse les outils utiles visibles s'ils sont beaux et pratiques.",
    "Choisis des contenants faciles à ouvrir d'une seule main.",
    "Fais une remise à zéro de deux minutes avant de quitter une pièce.",
    "Réserve une petite zone aux objets en transition.",
    "Mets un rappel près de l'action, pas loin dans ton téléphone.",
    "Évite de vider tout un placard en une fois.",
    "Travaille avec une boîte « garder », une boîte « donner » et un sac « jeter ».",
    "Célèbre la fin d'une tâche avant d'en choisir une autre.",
    "Garde un nombre réaliste de serviettes et de draps.",
    "Place une corbeille là où le papier s'accumule.",
    "Nettoie une tablette du frigo avant l'épicerie.",
    "Attribue une couleur à chaque membre de la maison.",
    "Utilise des crochets quand plier ou suspendre est trop exigeant.",
    "Prépare un petit kit de nettoyage transportable.",
    "Traite le courrier près du bac de recyclage.",
    "Laisse les doubles seulement là où ils sont vraiment utiles.",
    "Écris la prochaine action concrète, pas un grand projet.",
    "Découpe les tâches en blocs de cinq à dix minutes.",
    "Arrête-toi volontairement avant l'épuisement.",
    "Fais une vérification rapide du sol avant de passer l'aspirateur.",
    "Garde un plateau pour contenir les petits objets d'une surface.",
    "Réinitialise une seule zone chaque soir.",
    "Adapte ton système à tes gestes naturels.",
    "Utilise la règle « un entre, un sort » seulement si elle t'aide.",
    "Crée une liste « pas aujourd'hui » pour libérer ta tête.",
    "Mets la tâche la plus douce en premier.",
    "Préfère un rangement imparfait que tu utilises à un système parfait que tu évites."
  ];

  const tipEndings = [
    "Fais-en un essai sans chercher la perfection.",
    "Une version très simple est déjà utile.",
    "Adapte cette idée à ton énergie du jour.",
    "Tu peux t'arrêter après ce seul geste.",
    "Le meilleur système est celui que tu peux réellement utiliser."
  ];

  const tips = [];
  tipActions.forEach(function (action, actionIndex) {
    tipEndings.forEach(function (ending, endingIndex) {
      tips.push({
        id: "tip-" + String(actionIndex + 1).padStart(2, "0") + "-" + (endingIndex + 1),
        text: action + " " + ending
      });
    });
  });

  function zoneTask(id, titre, duree, categorie) {
    return { id: id, titre: titre, duree: duree, categorie: categorie };
  }

  const zones = [
    {
      id: "entry",
      number: 1,
      name: "Entrée et salle à manger",
      short: "Z1",
      description: "Faciliter les arrivées, les départs et les repas.",
      sections: ["Entrée", "Salle à manger"],
      tasks: [
        zoneTask("zone1_001", "Ranger les chaussures visibles", 5, "Entrée"),
        zoneTask("zone1_002", "Créer une place fixe pour les clés", 5, "Entrée"),
        zoneTask("zone1_003", "Trier le courrier accumulé", 10, "Entrée"),
        zoneTask("zone1_004", "Secouer ou aspirer le tapis", 5, "Entrée"),
        zoneTask("zone1_005", "Dégager le passage", 5, "Entrée"),
        zoneTask("zone1_006", "Préparer un panier pour les objets à sortir", 5, "Entrée"),
        zoneTask("zone1_007", "Nettoyer la poignée de la porte d'entrée", 2, "Entrée"),
        zoneTask("zone1_008", "Essuyer l'interrupteur de l'entrée", 2, "Entrée"),
        zoneTask("zone1_009", "Nettoyer la sonnette ou l'interphone", 5, "Entrée"),
        zoneTask("zone1_010", "Essuyer l'intérieur de la porte d'entrée", 5, "Entrée"),
        zoneTask("zone1_011", "Nettoyer le seuil de la porte", 5, "Entrée"),
        zoneTask("zone1_012", "Trier les manteaux hors saison", 15, "Entrée"),
        zoneTask("zone1_013", "Ranger les accessoires saisonniers", 10, "Entrée"),
        zoneTask("zone1_014", "Vider les pochettes des sacs accrochés", 10, "Entrée"),
        zoneTask("zone1_015", "Vérifier le contenu du sac de sortie", 5, "Entrée"),
        zoneTask("zone1_016", "Désencombrer la console d'entrée", 10, "Entrée"),
        zoneTask("zone1_017", "Essuyer la console d'entrée", 5, "Entrée"),
        zoneTask("zone1_018", "Nettoyer le miroir de l'entrée", 5, "Entrée"),
        zoneTask("zone1_019", "Regrouper les parapluies", 5, "Entrée"),
        zoneTask("zone1_020", "Réorganiser les crochets et les patères", 10, "Entrée"),
        zoneTask("zone1_021", "Retirer les papiers de la table à manger", 5, "Salle à manger"),
        zoneTask("zone1_022", "Essuyer la surface de la table à manger", 5, "Salle à manger"),
        zoneTask("zone1_023", "Nettoyer le dessous de la table", 10, "Salle à manger"),
        zoneTask("zone1_024", "Essuyer les dossiers et les assises des chaises", 10, "Salle à manger"),
        zoneTask("zone1_025", "Aspirer les miettes sur les chaises", 5, "Salle à manger"),
        zoneTask("zone1_026", "Aligner les chaises autour de la table", 2, "Salle à manger"),
        zoneTask("zone1_027", "Trier les nappes et les napperons", 10, "Salle à manger"),
        zoneTask("zone1_028", "Ranger la vaisselle utilisée pour les occasions", 15, "Salle à manger"),
        zoneTask("zone1_029", "Dépoussiérer le luminaire au-dessus de la table", 10, "Salle à manger"),
        zoneTask("zone1_030", "Essuyer la surface du buffet", 5, "Salle à manger"),
        zoneTask("zone1_031", "Désencombrer le dessus du buffet", 15, "Salle à manger"),
        zoneTask("zone1_032", "Trier un tiroir du buffet", 10, "Salle à manger"),
        zoneTask("zone1_033", "Nettoyer les poignées du buffet", 2, "Salle à manger"),
        zoneTask("zone1_034", "Dépoussiérer les objets décoratifs", 10, "Salle à manger"),
        zoneTask("zone1_035", "Nettoyer les plinthes de la salle à manger", 10, "Salle à manger"),
        zoneTask("zone1_036", "Essuyer le rebord de la fenêtre", 5, "Salle à manger"),
        zoneTask("zone1_037", "Nettoyer une vitre accessible", 10, "Salle à manger"),
        zoneTask("zone1_038", "Regrouper les bougies et les accessoires de table", 5, "Salle à manger"),
        zoneTask("zone1_039", "Préparer un centre de table simple", 5, "Salle à manger"),
        zoneTask("zone1_040", "Balayer sous la table à manger", 10, "Salle à manger")
      ]
    },
    {
      id: "kitchen",
      number: 2,
      name: "Cuisine",
      short: "Z2",
      description: "Retrouver un espace simple pour cuisiner et respirer.",
      sections: ["Cuisine"],
      tasks: [
        zoneTask("zone2_001", "Vider et rincer l'évier", 5, "Cuisine"),
        zoneTask("zone2_002", "Essuyer une section de comptoir", 5, "Cuisine"),
        zoneTask("zone2_003", "Vérifier cinq aliments dans le frigo", 5, "Cuisine"),
        zoneTask("zone2_004", "Nettoyer les poignées", 5, "Cuisine"),
        zoneTask("zone2_005", "Ranger les objets sans place sur la table", 10, "Cuisine"),
        zoneTask("zone2_006", "Balayer la zone la plus utilisée", 10, "Cuisine"),
        zoneTask("zone2_007", "Vider le lave-vaisselle", 10, "Cuisine"),
        zoneTask("zone2_008", "Ranger la vaisselle de l'égouttoir", 5, "Cuisine"),
        zoneTask("zone2_009", "Essuyer la plaque de cuisson", 10, "Cuisine"),
        zoneTask("zone2_010", "Nettoyer les boutons de la cuisinière", 5, "Cuisine"),
        zoneTask("zone2_011", "Essuyer le devant du réfrigérateur", 5, "Cuisine"),
        zoneTask("zone2_012", "Nettoyer l'intérieur du micro-ondes", 10, "Cuisine"),
        zoneTask("zone2_013", "Essuyer l'extérieur du micro-ondes", 5, "Cuisine"),
        zoneTask("zone2_014", "Trier une tablette du garde-manger", 10, "Cuisine"),
        zoneTask("zone2_015", "Regrouper les épices", 10, "Cuisine"),
        zoneTask("zone2_016", "Vérifier les dates des condiments", 10, "Cuisine"),
        zoneTask("zone2_017", "Essuyer une tablette du réfrigérateur", 10, "Cuisine"),
        zoneTask("zone2_018", "Nettoyer le bac à légumes", 15, "Cuisine"),
        zoneTask("zone2_019", "Retirer les aliments périmés du congélateur", 15, "Cuisine"),
        zoneTask("zone2_020", "Regrouper les aliments du congélateur", 10, "Cuisine"),
        zoneTask("zone2_021", "Essuyer les portes des armoires", 15, "Cuisine"),
        zoneTask("zone2_022", "Trier un tiroir d'ustensiles", 10, "Cuisine"),
        zoneTask("zone2_023", "Réorganiser le contenant d'ustensiles", 10, "Cuisine"),
        zoneTask("zone2_024", "Regrouper les contenants réutilisables", 15, "Cuisine"),
        zoneTask("zone2_025", "Associer les contenants à leurs couvercles", 10, "Cuisine"),
        zoneTask("zone2_026", "Ranger les sacs réutilisables", 5, "Cuisine"),
        zoneTask("zone2_027", "Nettoyer le couvercle de la poubelle", 5, "Cuisine"),
        zoneTask("zone2_028", "Essuyer le fond du bac à déchets", 10, "Cuisine"),
        zoneTask("zone2_029", "Nettoyer une section du dosseret", 10, "Cuisine"),
        zoneTask("zone2_030", "Faire briller le robinet", 5, "Cuisine"),
        zoneTask("zone2_031", "Détartrer la bouilloire", 15, "Cuisine"),
        zoneTask("zone2_032", "Nettoyer le filtre de la hotte", 15, "Cuisine"),
        zoneTask("zone2_033", "Essuyer les petits électroménagers", 10, "Cuisine"),
        zoneTask("zone2_034", "Désencombrer une armoire", 15, "Cuisine"),
        zoneTask("zone2_035", "Essuyer une tablette d'armoire", 10, "Cuisine"),
        zoneTask("zone2_036", "Regrouper les ingrédients de pâtisserie", 15, "Cuisine"),
        zoneTask("zone2_037", "Vider les miettes du grille-pain", 5, "Cuisine"),
        zoneTask("zone2_038", "Essuyer l'extérieur de la cafetière", 5, "Cuisine"),
        zoneTask("zone2_039", "Préparer une liste d'épicerie à partir des réserves", 10, "Cuisine"),
        zoneTask("zone2_040", "Laver une petite section du plancher", 15, "Cuisine")
      ]
    },
    {
      id: "bathroom",
      number: 3,
      name: "Salle de bain, buanderie et bureau",
      short: "Z3",
      description: "Créer de la fraîcheur dans les espaces de soin, de linge et de travail.",
      sections: ["Salle de bain", "Buanderie", "Bureau ou pièce supplémentaire"],
      tasks: [
        zoneTask("zone3_001", "Nettoyer le miroir", 5, "Salle de bain"),
        zoneTask("zone3_002", "Rafraîchir la toilette", 10, "Salle de bain"),
        zoneTask("zone3_003", "Changer les serviettes", 5, "Salle de bain"),
        zoneTask("zone3_004", "Jeter les contenants vides", 5, "Salle de bain"),
        zoneTask("zone3_005", "Essuyer le lavabo", 5, "Salle de bain"),
        zoneTask("zone3_006", "Regrouper les produits quotidiens", 10, "Salle de bain"),
        zoneTask("zone3_007", "Nettoyer la paroi ou le rideau de douche", 10, "Salle de bain"),
        zoneTask("zone3_008", "Rincer une tablette de douche", 5, "Salle de bain"),
        zoneTask("zone3_009", "Faire briller les robinets", 5, "Salle de bain"),
        zoneTask("zone3_010", "Dégager le comptoir de la salle de bain", 5, "Salle de bain"),
        zoneTask("zone3_011", "Trier un tiroir de produits de soin", 15, "Salle de bain"),
        zoneTask("zone3_012", "Laver le porte-brosses à dents", 5, "Salle de bain"),
        zoneTask("zone3_013", "Vider la petite poubelle", 5, "Salle de bain"),
        zoneTask("zone3_014", "Essuyer l'interrupteur et la poignée de porte", 2, "Salle de bain"),
        zoneTask("zone3_015", "Nettoyer le plancher autour de la toilette", 10, "Salle de bain"),
        zoneTask("zone3_016", "Rassembler le linge sale", 5, "Buanderie"),
        zoneTask("zone3_017", "Démarrer une brassée de lavage", 5, "Buanderie"),
        zoneTask("zone3_018", "Transférer une brassée dans la sécheuse", 5, "Buanderie"),
        zoneTask("zone3_019", "Plier les serviettes propres", 10, "Buanderie"),
        zoneTask("zone3_020", "Associer les chaussettes propres", 10, "Buanderie"),
        zoneTask("zone3_021", "Ranger le contenu d'un panier de linge", 15, "Buanderie"),
        zoneTask("zone3_022", "Nettoyer le joint de la laveuse", 10, "Buanderie"),
        zoneTask("zone3_023", "Essuyer la laveuse et la sécheuse", 5, "Buanderie"),
        zoneTask("zone3_024", "Vider le filtre à charpie", 2, "Buanderie"),
        zoneTask("zone3_025", "Trier les produits de lessive", 10, "Buanderie"),
        zoneTask("zone3_026", "Essuyer les bouchons des produits de lessive", 5, "Buanderie"),
        zoneTask("zone3_027", "Nettoyer le lavabo de la buanderie", 10, "Buanderie"),
        zoneTask("zone3_028", "Balayer le plancher de la buanderie", 10, "Buanderie"),
        zoneTask("zone3_029", "Ranger les cintres et le séchoir", 5, "Buanderie"),
        zoneTask("zone3_030", "Vérifier les poches avant le lavage", 5, "Buanderie"),
        zoneTask("zone3_031", "Dégager la surface du bureau", 10, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_032", "Classer cinq papiers", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_033", "Recycler les papiers devenus inutiles", 10, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_034", "Regrouper les crayons et les fournitures", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_035", "Trier un tiroir de bureau", 10, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_036", "Nettoyer le clavier et la souris", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_037", "Essuyer l'écran d'ordinateur", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_038", "Regrouper les câbles de recharge", 10, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_039", "Classer cinq documents numériques", 10, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_040", "Vider la poubelle du bureau", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_041", "Dépoussiérer la lampe de bureau", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_042", "Libérer la chaise du bureau", 5, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_043", "Trier une section de bibliothèque", 15, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_044", "Créer un plateau pour les papiers à traiter", 10, "Bureau ou pièce supplémentaire"),
        zoneTask("zone3_045", "Remettre en ordre le lit ou le canapé d'appoint", 10, "Bureau ou pièce supplémentaire")
      ]
    },
    {
      id: "bedroom",
      number: 4,
      name: "Chambre principale",
      short: "Z4",
      description: "Protéger un espace calme qui soutient le repos.",
      sections: ["Chambre principale"],
      tasks: [
        zoneTask("zone4_001", "Faire le lit simplement", 5, "Chambre principale"),
        zoneTask("zone4_002", "Dégager une table de chevet", 10, "Chambre principale"),
        zoneTask("zone4_003", "Ramasser les vêtements au sol", 5, "Chambre principale"),
        zoneTask("zone4_004", "Plier ou suspendre dix morceaux", 10, "Chambre principale"),
        zoneTask("zone4_005", "Libérer une chaise", 5, "Chambre principale"),
        zoneTask("zone4_006", "Préparer les vêtements de demain", 5, "Chambre principale"),
        zoneTask("zone4_007", "Ouvrir les rideaux", 2, "Chambre principale"),
        zoneTask("zone4_008", "Aérer la chambre", 5, "Chambre principale"),
        zoneTask("zone4_009", "Mettre le linge sale dans le panier", 5, "Chambre principale"),
        zoneTask("zone4_010", "Ranger une petite pile de vêtements propres", 10, "Chambre principale"),
        zoneTask("zone4_011", "Trier un tiroir de commode", 15, "Chambre principale"),
        zoneTask("zone4_012", "Réorganiser le tiroir de chaussettes", 10, "Chambre principale"),
        zoneTask("zone4_013", "Choisir cinq vêtements à donner", 10, "Chambre principale"),
        zoneTask("zone4_014", "Aligner les cintres dans la penderie", 5, "Chambre principale"),
        zoneTask("zone4_015", "Dégager le plancher du placard", 10, "Chambre principale"),
        zoneTask("zone4_016", "Trier une tablette du placard", 15, "Chambre principale"),
        zoneTask("zone4_017", "Dépoussiérer la tête de lit", 5, "Chambre principale"),
        zoneTask("zone4_018", "Essuyer la lampe de chevet", 5, "Chambre principale"),
        zoneTask("zone4_019", "Nettoyer les interrupteurs et les poignées", 2, "Chambre principale"),
        zoneTask("zone4_020", "Changer les taies d'oreiller", 5, "Chambre principale"),
        zoneTask("zone4_021", "Changer les draps", 15, "Chambre principale"),
        zoneTask("zone4_022", "Faire pivoter le matelas", 15, "Chambre principale"),
        zoneTask("zone4_023", "Aspirer sous une partie accessible du lit", 15, "Chambre principale"),
        zoneTask("zone4_024", "Retirer les objets alimentaires de la chambre", 5, "Chambre principale"),
        zoneTask("zone4_025", "Regrouper les câbles de la table de chevet", 5, "Chambre principale"),
        zoneTask("zone4_026", "Retirer les produits périmés de la table de chevet", 5, "Chambre principale"),
        zoneTask("zone4_027", "Trier les bijoux et les accessoires", 10, "Chambre principale"),
        zoneTask("zone4_028", "Regrouper les parfums et les produits de soin", 10, "Chambre principale"),
        zoneTask("zone4_029", "Essuyer le dessus de la commode", 5, "Chambre principale"),
        zoneTask("zone4_030", "Dépoussiérer les cadres et les décorations", 5, "Chambre principale"),
        zoneTask("zone4_031", "Nettoyer le miroir de la chambre", 5, "Chambre principale"),
        zoneTask("zone4_032", "Nettoyer les plinthes d'un mur", 10, "Chambre principale"),
        zoneTask("zone4_033", "Aspirer une petite section du plancher", 10, "Chambre principale"),
        zoneTask("zone4_034", "Laver une section accessible du plancher", 15, "Chambre principale"),
        zoneTask("zone4_035", "Ranger les pantoufles et les chaussures", 5, "Chambre principale"),
        zoneTask("zone4_036", "Créer un vide-poche pour les petits objets", 5, "Chambre principale"),
        zoneTask("zone4_037", "Trier les livres près du lit", 10, "Chambre principale"),
        zoneTask("zone4_038", "Retirer un objet qui nuit au repos", 2, "Chambre principale"),
        zoneTask("zone4_039", "Préparer les essentiels de la routine du soir", 5, "Chambre principale"),
        zoneTask("zone4_040", "Adoucir ou repositionner l'éclairage", 5, "Chambre principale")
      ]
    },
    {
      id: "living",
      number: 5,
      name: "Salon",
      short: "Z5",
      description: "Rendre la pièce accueillante sans viser la perfection.",
      sections: ["Salon"],
      tasks: [
        zoneTask("zone5_001", "Ramasser les objets qui appartiennent ailleurs", 10, "Salon"),
        zoneTask("zone5_002", "Replacer les coussins", 2, "Salon"),
        zoneTask("zone5_003", "Plier une couverture", 2, "Salon"),
        zoneTask("zone5_004", "Dégager la table basse", 5, "Salon"),
        zoneTask("zone5_005", "Rassembler les tasses et les verres", 5, "Salon"),
        zoneTask("zone5_006", "Libérer le passage au sol", 5, "Salon"),
        zoneTask("zone5_007", "Nettoyer sous les coussins du canapé", 10, "Salon"),
        zoneTask("zone5_008", "Essuyer les accoudoirs du canapé", 5, "Salon"),
        zoneTask("zone5_009", "Dépoussiérer l'écran du téléviseur", 5, "Salon"),
        zoneTask("zone5_010", "Essuyer les télécommandes", 2, "Salon"),
        zoneTask("zone5_011", "Regrouper les télécommandes au même endroit", 2, "Salon"),
        zoneTask("zone5_012", "Organiser les câbles du meuble multimédia", 10, "Salon"),
        zoneTask("zone5_013", "Dépoussiérer le meuble du téléviseur", 10, "Salon"),
        zoneTask("zone5_014", "Trier une tablette du meuble multimédia", 15, "Salon"),
        zoneTask("zone5_015", "Retirer les vieux magazines", 10, "Salon"),
        zoneTask("zone5_016", "Ranger les livres de la table basse", 5, "Salon"),
        zoneTask("zone5_017", "Essuyer une table d'appoint", 5, "Salon"),
        zoneTask("zone5_018", "Dépoussiérer les lampes du salon", 5, "Salon"),
        zoneTask("zone5_019", "Dépoussiérer une grille de ventilation", 5, "Salon"),
        zoneTask("zone5_020", "Dépoussiérer le cadre d'une fenêtre", 10, "Salon"),
        zoneTask("zone5_021", "Vérifier l'ouverture et le verrou d'une fenêtre", 5, "Salon"),
        zoneTask("zone5_022", "Dépoussiérer une section de stores ou de rideaux", 10, "Salon"),
        zoneTask("zone5_023", "Arroser les plantes du salon", 5, "Salon"),
        zoneTask("zone5_024", "Retirer les feuilles mortes des plantes", 5, "Salon"),
        zoneTask("zone5_025", "Dépoussiérer les feuilles d'une plante", 10, "Salon"),
        zoneTask("zone5_026", "Regrouper les objets décoratifs", 5, "Salon"),
        zoneTask("zone5_027", "Retirer un objet décoratif devenu inutile", 2, "Salon"),
        zoneTask("zone5_028", "Dépoussiérer les cadres du salon", 5, "Salon"),
        zoneTask("zone5_029", "Dégager une tablette", 10, "Salon"),
        zoneTask("zone5_030", "Dépoussiérer une tablette", 5, "Salon"),
        zoneTask("zone5_031", "Trier un panier de jeux ou de casse-têtes", 15, "Salon"),
        zoneTask("zone5_032", "Regrouper les jouets dans un panier", 10, "Salon"),
        zoneTask("zone5_033", "Trier les accessoires des animaux", 10, "Salon"),
        zoneTask("zone5_034", "Dégager le sol près du canapé", 5, "Salon"),
        zoneTask("zone5_035", "Aspirer la zone la plus fréquentée", 10, "Salon"),
        zoneTask("zone5_036", "Aspirer sous la table basse", 10, "Salon"),
        zoneTask("zone5_037", "Passer une vadrouille autour du canapé", 15, "Salon"),
        zoneTask("zone5_038", "Vider la poubelle du salon", 5, "Salon"),
        zoneTask("zone5_039", "Préparer un panier de lecture ou de détente", 5, "Salon"),
        zoneTask("zone5_040", "Remettre le salon à zéro avant la nuit", 5, "Salon")
      ]
    }
  ];

  const weeklyZones = [
    { id: "entry", name: "Entrée et salle à manger", description: "On facilite les arrivées, les départs et les repas.", color: "#dce9df" },
    { id: "kitchen", name: "Cuisine", description: "On redonne un peu d'air aux surfaces les plus utilisées.", color: "#f3e2cf" },
    { id: "bathroom", name: "Salle de bain et buanderie", description: "On crée une sensation de fraîcheur, une étape à la fois.", color: "#dfe9ed" },
    { id: "bedroom", name: "Chambre principale", description: "On protège le repos avec quelques gestes simples.", color: "#e7e1ee" },
    { id: "living", name: "Salon", description: "On apaise la pièce où la vie se rassemble.", color: "#eee4d4" }
  ];

  const defaultRoutines = [
    { id: "default-morning-1", routine: "morning", title: "Boire un verre d'eau", duration: "1 min", order: 0 },
    { id: "default-morning-2", routine: "morning", title: "Faire le lit simplement", duration: "3 min", order: 1 },
    { id: "default-morning-3", routine: "morning", title: "Dégager l'évier", duration: "5 min", order: 2 },
    { id: "default-afternoon-1", routine: "afternoon", title: "Faire un Room Rescue", duration: "5 min", order: 0 },
    { id: "default-afternoon-2", routine: "afternoon", title: "Ranger cinq objets", duration: "3 min", order: 1 },
    { id: "default-afternoon-3", routine: "afternoon", title: "Vérifier le panier de linge", duration: "2 min", order: 2 },
    { id: "default-evening-1", routine: "evening", title: "Préparer les vêtements de demain", duration: "4 min", order: 0 },
    { id: "default-evening-2", routine: "evening", title: "Faire une tournée des tasses", duration: "3 min", order: 1 },
    { id: "default-evening-3", routine: "evening", title: "Fermer la cuisine", duration: "5 min", order: 2 }
  ];

  window.APP_DATA = {
    quotes: quotes,
    missions: missions,
    tips: tips.slice(0, 365),
    zones: zones,
    weeklyZones: weeklyZones,
    defaultRoutines: defaultRoutines
  };
})();
